name: Pipeline

on:
  push:
    branches:
      - main

env:
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

jobs:
  Pipeline:
    name: Default
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Release
      run: ./.github/workflows/release.sh